version: '3.1'

services:

  web:
    depends_on:
      - db
    image: yourls
    restart: always
    container_name: yourls_newsite
    ports:
      - 80
    environment:
      VIRTUAL_HOST: newsite.fields.local
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: yourls_PASSWORD

      YOURLS_DB_HOST: db:3306
      YOURLS_SITE: http://newsite.fields.local
      YOURLS_USER: newsite
      YOURLS_PASS: newsite

  db:
    image: mysql
    container_name: yourls_mysql_newsite
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_PASSWORD
      MYSQL_USER: yourls
      MYSQL_PASSWORD: yourls_PASSWORD
      MYSQL_DATABASE: yourls

networks:
  default:
    external:
      name: nginx-proxy
